/* Visualize the distribution of numbers generated by
   the random function in ProcessingJS.
*/
var width = 600, height = 400;

void setup() {
    size(width, height);
    background(255, 255, 255);
}

// Set the initial variables and color
var randomCounts = [];
for(var i = 0; i < 20; i++) {
    randomCounts[i] = 0;
}

var rectWidth = floor(width / randomCounts.length);
noStroke();

// Animate the distribution of random numbers over time
void draw() {
    background(255, 255, 255);
    var index = floor(random(randomCounts.length));
    randomCounts[index]++;

    for(var i = 0; i < randomCounts.length; i++) {
        fill(77, 149, 34); // fill with gray green
        // paint rectangle, rect(x, y, w, h);
        rect(i * rectWidth, height - randomCounts[i], rectWidth-1, randomCounts[i]);
        fill(0, 0, 0); // fill with black color
        text(i, i * rectWidth + 3, height - 10);
    }
}
